import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { getCompanySetting } from "@/lib/company";
import { PrintButton } from "@/components/print-button";
import { LogoMark } from "@/components/logo";
import { formatDateTime, stopTypeLabels } from "@/lib/format";

export const dynamic = "force-dynamic";

export default async function PodCertificatePage({
  params,
}: {
  params: Promise<{ jobId: string }>;
}) {
  const { jobId } = await params;
  const [job, company] = await Promise.all([
    prisma.job.findUnique({
      where: { id: jobId },
      include: { customer: true, driver: true, stops: { orderBy: { sequence: "asc" } } },
    }),
    getCompanySetting(),
  ]);
  if (!job) notFound();

  return (
    <div>
      <div className="mb-4 flex justify-end print:hidden">
        <PrintButton label="Print / Save as PDF" />
      </div>

      <div className="rounded-xl bg-white p-10 shadow-card print:rounded-none print:p-0 print:shadow-none">
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3">
            <LogoMark size={44} className="rounded-xl" />
            <div className="text-lg font-semibold text-slate-900">{company.name}</div>
          </div>
          <div className="text-right">
            <div className="text-2xl font-semibold tracking-tight text-slate-900">PROOF OF DELIVERY</div>
            <div className="text-sm text-slate-500">{job.reference}</div>
          </div>
        </div>

        <div className="mt-6 grid grid-cols-2 gap-4 text-sm">
          <div>
            <span className="text-slate-500">Customer: </span>
            <span className="font-medium text-slate-900">{job.customer.name}</span>
          </div>
          <div className="text-right">
            <span className="text-slate-500">Driver: </span>
            <span className="font-medium text-slate-900">{job.driver?.name ?? "—"}</span>
          </div>
        </div>

        <div className="mt-6 space-y-4">
          {job.stops.map((s) => (
            <div key={s.id} className="rounded-lg border border-slate-200 p-4">
              <div className="flex items-center justify-between">
                <div className="font-medium text-slate-900">
                  Stop {s.sequence} · {stopTypeLabels[s.type]}
                </div>
                <div className="text-xs text-slate-500">
                  {s.completedAt ? formatDateTime(s.completedAt) : "Not completed"}
                </div>
              </div>
              <div className="mt-1 text-sm text-slate-600">
                {s.name ? `${s.name}, ` : ""}
                {s.addressLine1}
                {s.city ? `, ${s.city}` : ""} · {s.postcode}
              </div>
              {(s.podName || s.podSignature || s.podNotes) && (
                <div className="mt-3 flex items-end justify-between gap-4 border-t border-slate-100 pt-3">
                  <div className="text-sm">
                    <div className="text-slate-500">Received by</div>
                    <div className="font-medium text-slate-900">{s.podName ?? "—"}</div>
                    {s.podNotes && <div className="mt-1 text-xs text-slate-500">{s.podNotes}</div>}
                  </div>
                  {s.podSignature && (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img src={s.podSignature} alt="Signature" className="h-16 rounded border border-slate-200 bg-white" />
                  )}
                </div>
              )}
            </div>
          ))}
        </div>

        <p className="mt-8 text-center text-xs text-slate-400">
          Generated by {company.name} · {job.reference}
        </p>
      </div>
    </div>
  );
}
